# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: Information Mapping Cloud (LIVE)
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/imicloud?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
            hibernate.cache.region.factory_class: be.storefront.imicloud.config.jcache.SpringCacheRegionFactory
            hibernate.enable_lazy_load_no_trans: true
    cache:
        jcache:
            config: ehcache.xml
#    data:
#        elasticsearch:
#            cluster-name:
#            cluster-nodes: localhost:9300
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# IM Cloud specific properties
# ===================================================================

imcloud:
    # The base URL of the app. Must end with a "/"
    baseUrl: http://localhost:8080/

    cloudName: Information Mapping Cloud

    forgotPasswordUrl: http://localinformationmapping.com:10089/en/shop/customer/account/forgotPassword
    registerNewAccountUrl: http://localinformationmapping.com:10089/en/shop/customer/account/create

    # Enter the full path to the dir where images are stored. Must end with a "/"
    fileStorageDir: /Users/wouter/Business/Workspace/imi-publishing-cloud/uploads
    security:
        magento:
            allowMagentoCustomerLogin: true
            api:
                url: http://localinformationmapping.com:10089/magento/
                user: user
                pass: pass

        fsProCloud:
            api:
                url: http://fsprocloud.test.informationmapping.com:8081/
                user: MyTestUser
                pass: MyPwd

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: aee1b8c0456d55e87bb20919adf47ae0d519a41f
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: imicloud@localhost

    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: imicloud
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
