# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: FS Pro Cloud

    data:
        elasticsearch:
#            cluster-name:
            cluster-node: false
#            cluster-nodes:
#            properties:
#                path:
#                  logs: target/elasticsearch/log
#                  data: target/elasticsearch/data
    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://localhost:3306/imicloud?useUnicode=true&characterEncoding=utf8&useSSL=false
            name:
            username: root
            password: root
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 250
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.enable_lazy_load_no_trans: true
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true


# ===================================================================
# IM Cloud specific properties
# ===================================================================

imcloud:
    # The base URL of the app. Must end with a "/"
    baseUrl: http://localhost:8080/

    cloudName: Fs Pro Cloud

    forgotPasswordUrl: http://localinformationmapping.com:10089/en/shop/customer/account/forgotPassword
    registerNewAccountUrl: http://localinformationmapping.com:10089/en/shop/customer/account/create

    # Enter the full path to the dir where images are stored. Must end with a "/"
    fileStorageDir: /Users/wouter/Business/Workspace/imi-publishing-cloud/uploads
    security:
        magento:
            allowMagentoCustomerLogin: true
            api:
                url: http://localinformationmapping.com:10089/magento/
                user: user
                pass: pass

        fsProCloud:
            api:
                url: http://fsprocloud.test.informationmapping.com:8081/
                user: MyTestUser
                pass: MyPwd


# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: imicloud@localhost

    swagger:
        title: imicloud API
        description: imicloud API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
